In [88]:
import sklearn 
# Import all of the scikit learn stuff 
from __future__ import print_function 
from sklearn.decomposition import TruncatedSVD 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.preprocessing import Normalizer 
from sklearn import metrics 
from sklearn.cluster import KMeans, MiniBatchKMeans
import numpy

In [44]:
example = ["Machine learning is super fun",
           "Python is super, super cool",
           "Statistics is cool, too",
           "Data science is fun",
           "Python is great for machine learning",
           "I like football",           
           "Football is great to watch"] 
#vectorizer = CountVectorizer(min_df = 1, stop_words = 'english') 
#dtm = vectorizer.fit_transform(example) 

#pd.DataFrame(dtm.toarray(),index=example,columns=vectorizer.get_feature_names ()).head(10)


In [45]:
#import pandas as pd
#pd.DataFrame(dtm.toarray(),index=example,columns=vectorizer.get_feature_names ())

cool  data  football  fun  great  \
Machine learning is super fun            0     0         0    1      0   
Python is super, super cool              1     0         0    0      0   
Statistics is cool, too                  1     0         0    0      0   
Data science is fun                      0     1         0    1      0   
Python is great for machine learning     0     0         0    0      1   
I like football                          0     0         1    0      0   
Football is great to watch               0     0         1    0      1   

                                      learning  like  machine  python  \
Machine learning is super fun                1     0        1       0   
Python is super, super cool                  0     0        0       1   
Statistics is cool, too                      0     0        0       0   
Data science is fun                          0     0        0       0   
Python is great for machine learning         1     0        1       1   
I like football                              0     1        0       0   
Football is great to watch                   0     0        0       0   

                                      science  statistics  super  watch  
Machine learning is super fun               0           0      1      0  
Python is super, super cool                 0           0      2      0  
Statistics is cool, too                     0           1      0      0  
Data science is fun                         1           0      0      0  
Python is great for machine learning        0           0      0      0  
I like football                             0           0      0      0  
Football is great to watch                  0           0      0      1

# Computing tfidf

In [131]:
vectorizer = TfidfVectorizer(min_df = 1,lowercase=True,ngram_range=(1,1) ,stop_words = 'english') 
dtm = vectorizer.fit_transform(example) 
Df=pd.DataFrame(dtm.toarray(),index=example,columns=vectorizer.get_feature_names())
Df


cool      data  football       fun  \
Machine learning is super fun         0.000000  0.000000  0.000000  0.500000   
Python is super, super cool           0.408248  0.000000  0.000000  0.000000   
Statistics is cool, too               0.638709  0.000000  0.000000  0.000000   
Data science is fun                   0.000000  0.609819  0.000000  0.506202   
Python is great for machine learning  0.000000  0.000000  0.000000  0.000000   
I like football                       0.000000  0.000000  0.638709  0.000000   
Football is great to watch            0.000000  0.000000  0.538281  0.000000   

                                         great  learning      like  machine  \
Machine learning is super fun         0.000000       0.5  0.000000      0.5   
Python is super, super cool           0.000000       0.0  0.000000      0.0   
Statistics is cool, too               0.000000       0.0  0.000000      0.0   
Data science is fun                   0.000000       0.0  0.000000      0.0   
Python is great for machine learning  0.500000       0.5  0.000000      0.5   
I like football                       0.000000       0.0  0.769449      0.0   
Football is great to watch            0.538281       0.0  0.000000      0.0   

                                        python   science  statistics  \
Machine learning is super fun         0.000000  0.000000    0.000000   
Python is super, super cool           0.408248  0.000000    0.000000   
Statistics is cool, too               0.000000  0.000000    0.769449   
Data science is fun                   0.000000  0.609819    0.000000   
Python is great for machine learning  0.500000  0.000000    0.000000   
I like football                       0.000000  0.000000    0.000000   
Football is great to watch            0.000000  0.000000    0.000000   

                                         super     watch  
Machine learning is super fun         0.500000  0.000000  
Python is super, super cool           0.816497  0.000000  
Statistics is cool, too               0.000000  0.000000  
Data science is fun                   0.000000  0.000000  
Python is great for machine learning  0.000000  0.000000  
I like football                       0.000000  0.000000  
Football is great to watch            0.000000  0.648465

# #Computing SVD

In [90]:

lsa = TruncatedSVD(6, algorithm = 'arpack') 
dtm_lsa = lsa.fit_transform(dtm) 
dtm_lsa = Normalizer(copy=False).fit_transform(dtm_lsa)


In [91]:
dtm_lsa

array([[  8.96815500e-01,  -2.19195973e-01,  -2.83363812e-01,
         -6.01866189e-17,   1.88170616e-01,  -1.78806751e-01],
       [  6.52517988e-01,  -2.83963451e-01,   4.28368327e-01,
         -4.50540081e-16,   3.68489474e-01,   4.17493854e-01],
       [  1.99960232e-01,  -1.97671915e-01,   7.81499544e-01,
          3.16914215e-01,  -3.86584230e-01,  -2.45597628e-01],
       [  2.51781499e-01,  -1.39792754e-01,  -4.73614868e-01,
          8.06694758e-01,  -1.80859122e-01,   9.63668268e-02],
       [  7.76194477e-01,   1.56365927e-01,  -1.90450653e-01,
         -4.24137307e-01,  -3.05768133e-01,  -2.51820915e-01],
       [  1.16708133e-01,   7.39186363e-01,   1.71432912e-01,
          3.17399743e-01,   4.66954125e-01,  -3.02992965e-01],
       [  2.88318127e-01,   8.03884014e-01,   7.11385151e-02,
         -2.25203539e-16,  -3.36959061e-01,   3.89924419e-01]])

In [92]:
pd.DataFrame(lsa.components_,index = ["c1","c2","c3","c4","c5","c6"],columns = vectorizer.get_feature_names())

cool      data  football       fun     great  learning      like  \
c1  0.211903  0.082524  0.123490  0.293206  0.283966  0.425531  0.048611   
c2 -0.175362 -0.061554  0.654756 -0.124878  0.365768 -0.019431  0.413619   
c3  0.587499 -0.250362  0.128679 -0.322331 -0.046389 -0.193982  0.115162   
c4  0.201977  0.486642  0.201977  0.403955 -0.201977 -0.201977  0.243321   
c5 -0.130021 -0.144608  0.156812 -0.005022 -0.430023 -0.077978  0.474460   
c6  0.020413  0.103414  0.025145 -0.060843  0.154811 -0.360010 -0.413198   

     machine    python   science  statistics         super         watch  
c1  0.425531  0.343490  0.082524    0.083414  5.100288e-01  1.001567e-01  
c2 -0.019431 -0.029054 -0.061554   -0.110779 -2.405950e-01  3.751616e-01  
c3 -0.193982  0.071577 -0.250362    0.525787  1.875922e-01  3.985652e-02  
c4 -0.201977 -0.201977  0.486642    0.243321 -3.903529e-16 -1.439881e-16  
c5 -0.077978  0.003542 -0.144608   -0.393400  5.080836e-01 -2.855490e-01  
c6 -0.360010  0.085533  0.103414   -0.335440  4.510292e-01  4.434905e-01

In [93]:
pd.DataFrame(dtm_lsa, index = example, columns = ["c1","c2","c3","c4","c5","c6"])


c1        c2        c3  \
Machine learning is super fun         0.896815 -0.219196 -0.283364   
Python is super, super cool           0.652518 -0.283963  0.428368   
Statistics is cool, too               0.199960 -0.197672  0.781500   
Data science is fun                   0.251781 -0.139793 -0.473615   
Python is great for machine learning  0.776194  0.156366 -0.190451   
I like football                       0.116708  0.739186  0.171433   
Football is great to watch            0.288318  0.803884  0.071139   

                                                c4        c5        c6  
Machine learning is super fun        -6.018662e-17  0.188171 -0.178807  
Python is super, super cool          -4.505401e-16  0.368489  0.417494  
Statistics is cool, too               3.169142e-01 -0.386584 -0.245598  
Data science is fun                   8.066948e-01 -0.180859  0.096367  
Python is great for machine learning -4.241373e-01 -0.305768 -0.251821  
I like football                       3.173997e-01  0.466954 -0.302993  
Football is great to watch           -2.252035e-16 -0.336959  0.389924

In [99]:
S=lsa.explained_variance_
S=numpy.sort(S,axis=0)
Sreverse=S[::-1]
Sreverse

array([ 0.18060922,  0.15725663,  0.12135255,  0.10707598,  0.08023182,
        0.07199767])

In [106]:
print(lsa.components_.shape)
print(dtm_lsa.shape)
print((lsa.explained_variance_))
print(Sreverse)

(6L, 13L)
(7L, 6L)
[ 0.07199767  0.18060922  0.15725663  0.12135255  0.10707598  0.08023182]
[ 0.18060922  0.15725663  0.12135255  0.10707598  0.08023182  0.07199767]


In [142]:
a1=numpy.diag(Sreverse)
print(a1)
a2=numpy.zeros((6,6))
a2[0:4,0:4]=a1[0:4,0:4]
print(a2)

[[ 0.18060922  0.          0.          0.          0.          0.        ]
 [ 0.          0.15725663  0.          0.          0.          0.        ]
 [ 0.          0.          0.12135255  0.          0.          0.        ]
 [ 0.          0.          0.          0.10707598  0.          0.        ]
 [ 0.          0.          0.          0.          0.08023182  0.        ]
 [ 0.          0.          0.          0.          0.          0.07199767]]
[[ 0.18060922  0.          0.          0.          0.          0.        ]
 [ 0.          0.15725663  0.          0.          0.          0.        ]
 [ 0.          0.          0.12135255  0.          0.          0.        ]
 [ 0.          0.          0.          0.10707598  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [143]:
a3=numpy.dot(dtm_lsa,a2)
a4=numpy.dot(a3,lsa.components_)
featurenames=vectorizer.get_feature_names()
import pandas as pd
df=pd.DataFrame(a4,columns=featurenames,index=[1,2,3,4,5,6,7])

In [144]:
df

cool      data  football       fun     great  learning      like  \
1  0.020165  0.024098 -0.006992  0.062880  0.034982  0.076265 -0.010344   
2  0.063344 -0.000540 -0.007996  0.023375  0.014721  0.040933 -0.006755   
3  0.075674 -0.002336  0.003164 -0.002390 -0.012368 -0.009279  0.008077   
4 -0.002829  0.061530  0.001272  0.069497 -0.009908  0.013480  0.007516   
5  0.002643 -0.006259  0.021265  0.027137  0.059048  0.072833  0.003273   
6  0.003169  0.005915  0.088254 -0.001313  0.040674 -0.004189  0.059770   
7 -0.006062 -0.005646  0.090313 -0.003301  0.060625  0.018028  0.055814   

    machine    python   science  statistics     super     watch  
1  0.076265  0.054176  0.024098   -0.000751  0.084454  0.001920  
2  0.040933  0.045499 -0.000540    0.042110  0.080603 -0.002877  
3 -0.009279  0.013242 -0.002336    0.064577  0.043689 -0.004265  
4  0.013480 -0.005302  0.061530   -0.002973  0.017700 -0.005984  
5  0.072833  0.054957 -0.006259   -0.014233  0.061248  0.022345  
6 -0.004189 -0.001512  0.005915    0.008089 -0.013314  0.046550  
7  0.018028  0.014831 -0.005646   -0.005122 -0.002237  0.052986

In [145]:
test_example = ["Machine learning fun",
               "Python is  cool",
               "Statistics is cool, too",
               "Data science",
               "Python  or machine learning",
               "like football",           
               "Football is great"] 
#vectorizer = CountVectorizer(min_df = 1, stop_words = 'english') 
x = vectorizer.fit(example)
dtm_test = x.transform(test_example)

In [146]:
pd.DataFrame(dtm_test.toarray(),index=test_example,columns=vectorizer.get_feature_names ())

cool      data  football      fun     great  \
Machine learning fun         0.000000  0.000000  0.000000  0.57735  0.000000   
Python is  cool              0.707107  0.000000  0.000000  0.00000  0.000000   
Statistics is cool, too      0.638709  0.000000  0.000000  0.00000  0.000000   
Data science                 0.000000  0.707107  0.000000  0.00000  0.000000   
Python  or machine learning  0.000000  0.000000  0.000000  0.00000  0.000000   
like football                0.000000  0.000000  0.638709  0.00000  0.000000   
Football is great            0.000000  0.000000  0.707107  0.00000  0.707107   

                             learning      like  machine    python   science  \
Machine learning fun          0.57735  0.000000  0.57735  0.000000  0.000000   
Python is  cool               0.00000  0.000000  0.00000  0.707107  0.000000   
Statistics is cool, too       0.00000  0.000000  0.00000  0.000000  0.000000   
Data science                  0.00000  0.000000  0.00000  0.000000  0.707107   
Python  or machine learning   0.57735  0.000000  0.57735  0.577350  0.000000   
like football                 0.00000  0.769449  0.00000  0.000000  0.000000   
Football is great             0.00000  0.000000  0.00000  0.000000  0.000000   

                             statistics  super  watch  
Machine learning fun           0.000000    0.0    0.0  
Python is  cool                0.000000    0.0    0.0  
Statistics is cool, too        0.769449    0.0    0.0  
Data science                   0.000000    0.0    0.0  
Python  or machine learning    0.000000    0.0    0.0  
like football                  0.000000    0.0    0.0  
Football is great              0.000000    0.0    0.0

In [147]:
lsa = TruncatedSVD(6, algorithm = 'arpack') 
x = lsa.fit(dtm)
dtm_lsa_test = x.transform(dtm_test) 
#dtm_lsa_test = Normalizer(copy=False).fit_transform(dtm_lsa_test)

In [148]:
pd.DataFrame(x.components_,index = ["c1","c2","c3","c4","c5","c6"],columns = vectorizer.get_feature_names())

cool      data  football       fun     great  learning      like  \
c1  0.211903  0.082524  0.123490  0.293206  0.283966  0.425531  0.048611   
c2 -0.175362 -0.061554  0.654756 -0.124878  0.365768 -0.019431  0.413619   
c3  0.587499 -0.250362  0.128679 -0.322331 -0.046389 -0.193982  0.115162   
c4  0.201977  0.486642  0.201977  0.403955 -0.201977 -0.201977  0.243321   
c5 -0.130021 -0.144608  0.156812 -0.005022 -0.430023 -0.077978  0.474460   
c6  0.020413  0.103414  0.025145 -0.060843  0.154811 -0.360010 -0.413198   

     machine    python   science  statistics         super         watch  
c1  0.425531  0.343490  0.082524    0.083414  5.100288e-01  1.001567e-01  
c2 -0.019431 -0.029054 -0.061554   -0.110779 -2.405950e-01  3.751616e-01  
c3 -0.193982  0.071577 -0.250362    0.525787  1.875922e-01  3.985652e-02  
c4 -0.201977 -0.201977  0.486642    0.243321  4.112404e-16 -3.959672e-16  
c5 -0.077978  0.003542 -0.144608   -0.393400  5.080836e-01 -2.855490e-01  
c6 -0.360010  0.085533  0.103414   -0.335440  4.510292e-01  4.434905e-01

In [149]:
pd.DataFrame(dtm_lsa_test,index = test_example,columns = ["c1","c2","c3","c4","c5","c6"] )

c1        c2        c3            c4  \
Machine learning fun         0.660643 -0.094536 -0.410089  8.604228e-16   
Python is  cool              0.392722 -0.144544  0.466037 -3.885781e-16   
Statistics is cool, too      0.199527 -0.197244  0.779807  3.162278e-01   
Data science                 0.116707 -0.087051 -0.354066  6.882159e-01   
Python  or machine learning  0.689675 -0.039212 -0.182666 -3.498351e-01   
like football                0.116277  0.736457  0.170800  3.162278e-01   
Football is great            0.288115  0.721619  0.058188 -5.828671e-16   

                                   c5        c6  
Machine learning fun        -0.092940 -0.450831  
Python is  cool             -0.089435  0.074915  
Statistics is cool, too     -0.385747 -0.245066  
Data science                -0.204507  0.146250  
Python  or machine learning -0.087996 -0.366321  
like football                0.465230 -0.301874  
Football is great           -0.193189  0.127248

#### 

In [154]:
print(a4.shape)


(7L, 13L)


In [155]:
import numpy as np
a=np.dot(dtm_lsa_test,x.components_)
a
pd.DataFrame(a,index = example,columns = vectorizer.get_feature_names())


cool      data  football       fun  \
Machine learning is super fun        -0.081475  0.129827 -0.058996  0.365591   
Python is super, super cool           0.395521 -0.054691  0.001684 -0.021128   
Statistics is cool, too               0.644029  0.017701 -0.006943 -0.023632   
Data science is fun                   0.000562  0.483247  0.022466  0.429353   
Python is great for machine learning -0.020991 -0.090341 -0.057681  0.147405   
I like football                      -0.006943 -0.023103  0.647771  0.030843   
Football is great to watch           -0.003591  0.005886  0.488456 -0.031165   

                                         great  learning      like   machine  \
Machine learning is super fun         0.142219  0.532062  0.087971  0.532062   
Python is super, super cool           0.087088  0.059525 -0.060414  0.059525   
Statistics is cool, too               0.012409 -0.008096  0.013104 -0.008096   
Data science is fun                  -0.010695 -0.055672 -0.061111 -0.055672   
Python is great for machine learning  0.241764  0.539074  0.020761  0.539074   
I like football                      -0.016196  0.010566  0.752346  0.010566   
Football is great to watch            0.445836  0.066546  0.174943  0.066546   

                                        python   science  statistics  \
Machine learning is super fun         0.161428  0.129827    0.037749   
Python is super, super cool           0.178544 -0.054691    0.303861   
Statistics is cool, too               0.043884  0.017701    0.759409   
Data science is fun                  -0.109945  0.483247    0.032067   
Python is great for machine learning  0.263976 -0.090341    0.038203   
I like football                      -0.057275 -0.023103    0.013104   
Football is great to watch            0.092363  0.005886    0.008003   

                                         super     watch  
Machine learning is super fun         0.032203 -0.159043  
Python is super, super cool           0.310850  0.062443  
Statistics is cool, too              -0.011017 -0.021469  
Data science is fun                  -0.023896  0.088176  
Python is great for machine learning  0.116991 -0.090249  
I like football                       0.014379  0.028020  
Football is great to watch           -0.056519  0.413498

In [156]:
matrix_similarity = numpy.asarray(numpy.asmatrix(dtm_lsa_test) * numpy.asmatrix(dtm_lsa_test).T) 
pd.DataFrame(matrix_similarity,index=test_example, columns=example)

Machine learning is super fun  \
Machine learning fun                              0.825446   
Python is  cool                                   0.056536   
Statistics is cool, too                          -0.022992   
Data science                                      0.183602   
Python  or machine learning                       0.707573   
like football                                     0.030008   
Football is great                                 0.058847   

                             Python is super, super cool  \
Machine learning fun                            0.056536   
Python is  cool                                 0.405925   
Statistics is cool, too                         0.486428   
Data science                                   -0.077345   
Python  or machine learning                     0.171816   
like football                                  -0.045409   
Football is great                               0.062772   

                             Statistics is cool, too  Data science is fun  \
Machine learning fun                       -0.022992             0.183602   
Python is  cool                             0.486428            -0.077345   
Statistics is cool, too                     0.995673             0.025034   
Data science                                0.025034             0.683414   
Python  or machine learning                 0.015988            -0.127762   
like football                               0.005648            -0.032672   
Football is great                           0.003865             0.008323   

                             Python is great for machine learning  \
Machine learning fun                                     0.707573   
Python is  cool                                          0.171816   
Statistics is cool, too                                  0.015988   
Data science                                            -0.127762   
Python  or machine learning                              0.774875   
like football                                           -0.020867   
Football is great                                        0.130167   

                             I like football  Football is great to watch  
Machine learning fun                0.030008                    0.058847  
Python is  cool                    -0.045409                    0.062772  
Statistics is cool, too             0.005648                    0.003865  
Data science                       -0.032672                    0.008323  
Python  or machine learning        -0.020867                    0.130167  
like football                       0.992629                    0.446591  
Football is great                   0.446591                    0.660644

In [25]:
m1 = np.array([1,2,3])
m1

array([1, 2, 3])

In [33]:
m2=np.array([1,2,3])
m2

array([-1, -2, -3])

In [27]:
similarity = np.asarray(numpy.asmatrix(m1) * numpy.asmatrix(m2).T)

In [28]:
similarity

array([[32]])

In [34]:
from numpy import dot
from numpy.linalg import norm

cos_sim = dot(m1, m2)/(norm(m1)*norm(m2))
cos_sim

-1.0

In [37]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([1, 0, 1], [1,0, 1])

C:\Users\Shiva\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shiva\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 1.]])